version: '3'
services:
  api:
    image: "ce-3.8.1:hf-eai-dev-demo"
    build: ./mule
    networks:
     - my_network
    volumes:
     - /mule-apps/apps/3.8.1/logs:/root/mule/logs
    env_file:
     - dev.properties
     
  nginx:
    image: "nginx:mule"
    build: ./nginx
    networks:
     - my_network
    ports:
     - "89:80"

networks:
  my_network:
