version: '3'
services:
  api1:
    container_name: api1
    image: "abacchus/ce-3.8.1"
    build: ./mule
    networks:
     - my_network
    volumes:
     - /mule-apps/apps/3.8.1/logs:/root/mule/logs
     - /mule-apps/apps/3.8.1/app:/root/mule/apps
    env_file:
     - dev.properties
    
  api2:
    container_name: api2
    image: "abacchus/ce-3.8.1"
    build: ./mule
    networks:
     - my_network
    volumes:
     - /mule-apps/apps/3.8.1/logs:/root/mule/logs
     - /mule-apps/apps/3.8.1/app:/root/mule/apps
    env_file:
     - dev.properties

  nginx:
    container_name: nginx
    image: "nginx:mule"
    build: ./nginx
    networks:
     - my_network
    ports:
     - "89:80"

networks:
  my_network:
