pipeline {
    agent {dockerfile true}
    environment{
        t = "hello"
    }

    stages{
        stage("test"){
            steps{
                echo "${t}"
                echo "${JOB_NAME}"
            }
        }
    }
}
